<?php

namespace App\Imports;

use App\Models\Data;
use http\Exception;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class ConstructionImport implements ToCollection, WithHeadingRow
{
    private $competence, $upload_data;
    public function __construct($competence, $upload_data)
    {
        $this->competence = $competence;
        $this->upload_data = $upload_data;
    }

    public function collection(Collection $rows)
    {
        $contador = 0;
        foreach ($rows as $row) {
            try {
                Data::create([
                    'construction' => $row['obra_id'],
                    'uploaddata' => $this->upload_data->id,
                    'CUSTOP' => $row['custop'],
                    'PRAZO' => $row['prazo'],
                    'FLUXOD' => $row['fluxod'],
                    'QUALIDADE' => $row['qualidade'],
                    'SEGORG' => $row['segorg'],
                    'MAMBI' => $row['mambi'],
                    'ACUMCONTR' => $row['acumcontr'],
                    'FASE'=>$row['fase'],
                    'AREACONSTRM2' => $row['areaconstrm2'],
                    'NUNITQTD' => $row['nunitqtd'],
                    'CORPRRATUAL' => $row['corprratual'],
                    'CORRPRATUALFAROL' => $row['corrpratualfarol'],
                    'CORRPRATUALVLR' => $row['corrpratualvlr'],
                    'FXDPRRATUAL' => $row['fxdprratual'],
                    'FXDRPRATUALFAROL' => $row['fxdrpratualfarol'],
                    'FXDRPRATUALVLR' => $row['fxdrpratualvlr'],
                    'FPRPRFAROL' => $row['fprprfarol'],
                    'FPRPR' => $row['fprpr'],
                    'POTEROBRARPMESFAROL' => $row['poterobrarpmesfarol'],
                    'POTEROBRARPMES' => $row['poterobrarpmes'],
                    'POECOPR' => $row['poecopr'],
                    'IDQFAROL' => $row['idqfarol'],
                    'IDSFAROL' => $row['idsfarol'],
                    'PORCCONTRATINDIC' => $row['porccontratindic'],
                    'ACORCPROOJATUAL' => $row['acorcproojatual'],
                    'APORCPROOJATUAL' => $row['aporcproojatual'],
                    'FBP' => $row['fbp'],
                    'FBR' => $row['fbr'],
                    'FBD' => $row['fbd'],
                    'FOP' => $row['fop'],
                    'FOR' => $row['for'],
                    'FOD' => $row['fod'],
                    'FOBP' => $row['fobp'],
                    'FOBR' => $row['fobr'],
                    'FOBD' => $row['fobd'],
                    'AREATERRENO' => $row['areaterreno'],
                    'AREACONSTRUIDA' => $row['areaconstruida'],
                    'AREAPRIVATIVA' => $row['areaprivativa'],
                    'AREAEQUIVNB' => $row['areaequivnb'],
                    'AREADEGARGAGEM' => $row['areadegargagem'],
                    'EFECIEPROJ' => $row['efecieproj'],
                    'TIPOEMPREEND' => $row['tipoempreend'],
                    'SISTCONSTRUTIVO' => $row['sistconstrutivo'],
                    'NDETORRESPVTOS' => $row['ndetorrespvtos'],
                    'NPVTOSGARGAGEM' => $row['npvtosgargagem'],
                    'NUNIDADES' => $row['nunidades'],
                    'AREAAPARTAMENTOS' => $row['areaapartamentos'],
                    'AGENTEFINANCEIRO' => $row['agentefinanceiro'],
                    'DATAVISTORIA' => $row['datavistoria'],
                    'VALORFINANCIAMENTO' => $row['valorfinanciamento'],
                    'ORCCONTRATUAL' => $row['orccontratual'],
                    'CUSTORASOOBRA' => $row['custorasoobra'],
                    'TAXAADM' => $row['taxaadm'],
                    'CUSTORASOTAXA' => $row['custorasotaxa'],
                    'MANUTENCAO' => $row['manutencao'],
                    'CUSTOSDIVERSOS' => $row['custosdiversos'],
                    'ORCCONTRATUALINCC' => $row['orccontratualincc'],
                    'CUSTORASOOBRAINCC' => $row['custorasoobraincc'],
                    'TAXAADMINCC' => $row['taxaadmincc'],
                    'CUSTORASOTAXAINCC' => $row['custorasotaxaincc'],
                    'MANUTENCAOINCC' => $row['manutencaoincc'],
                    'CUSTOSDIVERSOSINCC' => $row['custosdiversosincc'],
                    'INICIOPLANOBRAPREV' => $row['inicioplanobraprev'],
                    'TERMPLANOBRAPREV' => $row['termplanobraprev'],
                    'TERMHABITESEPREV' => $row['termhabiteseprev'],
                    'TERMCLIENTEPREV' => $row['termclienteprev'],
                    'PRAZOBRAMESESPREV' => $row['prazobramesesprev'],
                    'INICIOPLANOBRAREAL' => $row['inicioplanobrareal'],
                    'TERMPLANOBRAREAL' => $row['termplanobrareal'],
                    'TERMHABITESEREAL' => $row['termhabitesereal'],
                    'TERMCLIENTEREAL' => $row['termclientereal'],
                    'PRAZOOBRAMESESREAL' => $row['prazoobramesesreal'],
                    'INICIOPLANOBRADESV' => $row['inicioplanobradesv'],
                    'TERMPLANOBRADESV' => $row['termplanobradesv'],
                    'TERMHABITESEDESV' => $row['termhabitesedesv'],
                    'TERMCLIENTEDESV' => $row['termclientedesv'],
                    'PRAZOOBRAMESESDESV' => $row['prazoobramesesdesv'],
                    'INICIOPLANOBRAFAROL' => $row['inicioplanobrafarol'],
                    'TERMPLANOBRAFAROL' => $row['termplanobrafarol'],
                    'TERMHABITESEFAROL' => $row['termhabitesefarol'],
                    'TERMCLIENTEFAROL' => $row['termclientefarol'],
                    'PRAZOOBRAMESESFAROL' => $row['prazoobramesesfarol'],
                    'EVOORCID' => $row['evoorcid'],
                    'EVOORCINIOBRA' => $row['evoorciniobra'],
                    'EVOORCADTV' => $row['evoorcadtv'],
                    'EVOORCREVOBRA' => $row['evoorcrevobra'],
                    'EVOORCIDINCC' => $row['evoorcidincc'],
                    'EVOORCINIOBRAINCC' => $row['evoorciniobraincc'],
                    'EVOORCADTVINCC' => $row['evoorcadtvincc'],
                    'EVOORCREVOBRAINCC' => $row['evoorcrevobraincc'],
                    'ACOFACUMTOTAL' => $row['acofacumtotal'],
                    'ACOFSALDOREAL' => $row['acofsaldoreal'],
                    'ACOFPROJCUSTO' => $row['acofprojcusto'],
                    'ACOFVARORCREV' => $row['acofvarorcrev'],
                    'ACOFACUMTOTALINCC' => $row['acofacumtotalincc'],
                    'ACOFSALDOREALINCC' => $row['acofsaldorealincc'],
                    'ACOFPROJCUSTOINCC' => $row['acofprojcustoincc'],
                    'ACOFVARORCREVINCC' => $row['acofvarorcrevincc'],
                    'ACOFVARORCREVVALOR' => $row['acofvarorcrevvalor'],
                    'ACOFVARORCREVFAROL' => $row['acofvarorcrevfarol'],
                    'ACOFINCCIN' => $row['acofinccin'],
                    'CUSTOM2PROJCONST' => $row['custom2projconst'],
                    'CUSTOM2PROJPRIVA' => $row['custom2projpriva'],
                    'CUSTOM2PROJCONSTINCC' => $row['custom2projconstincc'],
                    'CUSTOM2PROJPRIVAINCC' => $row['custom2projprivaincc'],
                    'PROJEXEC' => $row['projexec'],
                    'FUNDACAOTORRE' => $row['fundacaotorre'],
                    'ESTRUTURATORRE' => $row['estruturatorre'],
                    'INSTALACOES' => $row['instalacoes'],
                    'ACABAMENTO' => $row['acabamento'],
                    'REVFACHADA' => $row['revfachada'],
                    'AEPAISAGISMO' => $row['aepaisagismo'],
                    'flamemeses' => $row['flamemeses'],
                    'flameperiodofisprev' => $row['flameperiodofisprev'],
                    'flameperiodofisprevmesatual' => $row['flameperiodofisprevmesatual'],
                    'flameacumulofisreal' => $row['flameacumulofisreal'],
                    'flameacumulofisprev' => $row['flameacumulofisprev'],
                    'flameacumulofisproj' => $row['flameacumulofisproj'],
                    'flameperiodofissubprev' => $row['flameperiodofissubprev'],
                    'flameperiodofisproj' => $row['flameperiodofisproj'],
                    'dfmeses' => $row['dfmeses'],
                    'dfperiodofisprev' => $row['dfperiodofisprev'],
                    'dfperiodofisprevmesatual' => $row['dfperiodofisprevmesatual'],
                    'dfacumulofisreal' => $row['dfacumulofisreal'],
                    'dfacumulofisprev' => $row['dfacumulofisprev'],
                    'dfacumulofisproj' => $row['dfacumulofisproj'],
                    'dfperiodofissubprev' => $row['dfperiodofissubprev'],
                    'dfperiodofisproj' => $row['dfperiodofisproj'],
                    'aaprevfisobra' => $row['aaprevfisobra'],
                    'aarealfisobra' => $row['aarealfisobra'],
                    'npprevfisobra' => $row['npprevfisobra'],
                    'nprealfisobra' => $row['nprealfisobra'],
                    'atprevfisobra' => $row['atprevfisobra'],
                    'atrealfisobra' => $row['atrealfisobra'],
                    'dtprevfisobra' => $row['dtprevfisobra'],
                    'dtrealfisobra' => $row['dtrealfisobra'],
                    'dtprevfisobrafarol' => $row['dtprevfisobrafarol'],
                    'dtrealfisobrafarol' => $row['dtrealfisobrafarol'],
                    'aaprevfisbanco' => $row['aaprevfisbanco'],
                    'aarealfisbanco' => $row['aarealfisbanco'],
                    'npprevfisbanco' => $row['npprevfisbanco'],
                    'nprealfisbanco' => $row['nprealfisbanco'],
                    'atprevfisbanco' => $row['atprevfisbanco'],
                    'atrealfisbanco' => $row['atrealfisbanco'],
                    'dtprevfisbanco' => $row['dtprevfisbanco'],
                    'dtrealfisbanco' => $row['dtrealfisbanco'],
                    'dtprevfisbancofarol' => $row['dtprevfisbancofarol'],
                    'dtrealfisbancofarol' => $row['dtrealfisbancofarol'],
                    'aaprevfinbanco' => $row['aaprevfinbanco'],
                    'aarealfinbanco' => $row['aarealfinbanco'],
                    'npprevfinbanco' => $row['npprevfinbanco'],
                    'nprealfinbanco' => $row['nprealfinbanco'],
                    'atprevfinbanco' => $row['atprevfinbanco'],
                    'atrealfinbanco' => $row['atrealfinbanco'],
                    'dtprevfinbanco' => $row['dtprevfinbanco'],
                    'dtrealfinbanco' => $row['dtrealfinbanco'],
                    'dtprevfinbancofarol' => $row['dtprevfinbancofarol'],
                    'dtrealfinbancofarol' => $row['dtrealfinbancofarol'],
                    'ffomeses' => $row['ffomeses'],
                    'ffodelta' => $row['ffodelta'],
                    'ffoprevrev' => $row['ffoprevrev'],
                    'fforeal' => $row['fforeal'],
                    'fdmeses' => $row['fdmeses'],
                    'fddelta' => $row['fddelta'],
                    'fdprevrev' => $row['fdprevrev'],
                    'fdreal' => $row['fdreal']
                ]);
                /*
                 *
                 *
                Data::create([
                    'construction' => $row[0],
                    'uploaddata' => $this->upload_data->id,
                    'CUSTOP' => $row[1],
                    'PRAZO' => $row[2],
                    'FLUXOD' => $row[3],
                    'QUALIDADE' => $row[4],
                    'SEGORG' => $row[5],
                    'MAMBI' => $row[6],
                    'ACUMCONTR' => $row[7],
                    'FASE'=>$row[8],
                    'AREACONSTRM2' => $row[9],
                    'NUNITQTD' => $row[10],
                    'CORPRRATUAL' => $row[11],
                    'CORRPRATUALFAROL' => $row[12],
                    'CORRPRATUALVLR' => $row[13],
                    'FXDPRRATUAL' => $row[14],
                    'FXDRPRATUALFAROL' => $row[15],
                    'FXDRPRATUALVLR' => $row[16],
                    'FPRPRFAROL' => $row[17],
                    'FPRPR' => $row[18],
                    'POTEROBRARPMESFAROL' => $row[19],
                    'POTEROBRARPMES' => $row[20],
                    'POECOPR' => $row[21],
                    'IDQFAROL' => $row[22],
                    'IDSFAROL' => $row[23],
                    'PORCCONTRATINDIC' => $row[24],
                    'ACORCPROOJATUAL' => $row[25],
                    'APORCPROOJATUAL' => $row[26],
                     'FBP' => $row[27],
                     'FBR' => $row[28],
                     'FBD' => $row[29],
                     'FOP' => $row[30],
                     'FOR' => $row[31],
                     'FOD' => $row[32],
                     'FOBP' => $row[33],
                     'FOBR' => $row[34],
                     'FOBD' => $row[35],
                     'AREATERRENO' => $row[36],
                     'AREACONSTRUIDA' => $row[37],
                     'AREAPRIVATIVA' => $row[38],
                     'AREAEQUIVNB' => $row[39],
                     'AREADEGARGAGEM' => $row[40],
                     'EFECIEPROJ' => $row[41],
                     'TIPOEMPREEND' => $row[42],
                     'SISTCONSTRUTIVO' => $row[43],
                     'NDETORRESPVTOS' => $row[44],
                     'NPVTOSGARGAGEM' => $row[45],
                     'NUNIDADES' => $row[46],
                     'AREAAPARTAMENTOS' => $row[47],
                     'AGENTEFINANCEIRO' => $row[48],
                     'DATAVISTORIA' => $row[49],
                     'VALORFINANCIAMENTO' => $row[50],
                     'ORCCONTRATUAL' => $row[51],
                     'CUSTORASOOBRA' => $row[52],
                     'TAXAADM' => $row[53],
                     'CUSTORASOTAXA' => $row[54],
                     'MANUTENCAO' => $row[55],
                     'CUSTOSDIVERSOS' => $row[56],
                     'ORCCONTRATUALINCC' => $row[57],
                     'CUSTORASOOBRAINCC' => $row[58],
                     'TAXAADMINCC' => $row[59],
                     'CUSTORASOTAXAINCC' => $row[60],
                     'MANUTENCAOINCC' => $row[61],
                     'CUSTOSDIVERSOSINCC' => $row[62],
                     'INICIOPLANOBRAPREV' => $row[63],
                     'TERMPLANOBRAPREV' => $row[64],
                     'TERMHABITESEPREV' => $row[65],
                     'TERMCLIENTEPREV' => $row[66],
                     'PRAZOBRAMESESPREV' => $row[67],
                     'INICIOPLANOBRAREAL' => $row[68],
                     'TERMPLANOBRAREAL' => $row[69],
                     'TERMHABITESEREAL' => $row[70],
                     'TERMCLIENTEREAL' => $row[71],
                     'PRAZOOBRAMESESREAL' => $row[72],
                     'INICIOPLANOBRADESV' => $row[73],
                     'TERMPLANOBRADESV' => $row[74],
                     'TERMHABITESEDESV' => $row[75],
                     'TERMCLIENTEDESV' => $row[76],
                     'PRAZOOBRAMESESDESV' => $row[77],
                     'INICIOPLANOBRAFAROL' => $row[78],
                     'TERMPLANOBRAFAROL' => $row[79],
                     'TERMHABITESEFAROL' => $row[80],
                     'TERMCLIENTEFAROL' => $row[81],
                     'PRAZOOBRAMESESFAROL' => $row[82],
                     'EVOORCID' => $row[83],
                     'EVOORCINIOBRA' => $row[84],
                     'EVOORCADTV' => $row[85],
                     'EVOORCREVOBRA' => $row[86],
                     'EVOORCIDINCC' => $row[87],
                     'EVOORCINIOBRAINCC' => $row[88],
                     'EVOORCADTVINCC' => $row[89],
                     'EVOORCREVOBRAINCC' => $row[90],
                     'ACOFACUMTOTAL' => $row[91],
                     'ACOFSALDOREAL' => $row[92],
                     'ACOFPROJCUSTO' => $row[93],
                     'ACOFVARORCREV' => $row[94],
                     'ACOFACUMTOTALINCC' => $row[95],
                     'ACOFSALDOREALINCC' => $row[96],
                     'ACOFPROJCUSTOINCC' => $row[97],
                     'ACOFVARORCREVINCC' => $row[98],
                     'ACOFVARORCREVVALOR' => $row[99],
                     'ACOFVARORCREVFAROL' => $row[100],
                     'ACOFINCCIN' => $row[101],
                     'CUSTOM2PROJCONST' => $row[102],
                     'CUSTOM2PROJPRIVA' => $row[103],
                     'CUSTOM2PROJCONSTINCC' => $row[104],
                     'CUSTOM2PROJPRIVAINCC' => $row[105],
                     'PROJEXEC' => $row[106],
                     'FUNDACAOTORRE' => $row[107],
                     'ESTRUTURATORRE' => $row[108],
                     'INSTALACOES' => $row[109],
                     'ACABAMENTO' => $row[110],
                     'REVFACHADA' => $row[111],
                     'AEPAISAGISMO' => $row[112]
                ]);*/
                $contador++;
            }catch(Exception $e){
                $this->upload_data->uploadstatus = 3;
                $this->upload_data->update();
            }
        }
        $this->upload_data->uploadstatus = 2;
        $this->upload_data->linecount = $contador;
        $this->upload_data->update();
    }

    public function headingRow(): int
    {
        return 1;
    }
}
